name: Full Deployment - Frontend & Backend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  # ---------------------------
  # 1️⃣ Frontend Job - React
  # ---------------------------
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ------------------- Node.js caching -------------------
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci  # faster and deterministic install

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          force_orphan: true

  # ---------------------------
  # 2️⃣ Backend Job - Python
  # ---------------------------
  backend:
    runs-on: ubuntu-latest
    needs: frontend
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ------------------- Pip caching -------------------
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package backend for deployment
        working-directory: ./backend
        run: zip -r ../backend-package.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-package
          path: backend-package.zip

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'evcsapi'
          slot-name: 'Production'
          package: backend-package.zip
