name: Deploy React Frontend to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'                         # only trigger on frontend folder changes
      - '.github/workflows/frontend-deploy.yml'  # or this workflow file itself
  workflow_dispatch:

permissions:
  contents: write  # needed to push to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3️⃣ Cache npm dependencies
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4️⃣ Ensure homepage is set
      - name: Ensure homepage field in package.json
        run: |
          npm pkg set homepage="https://Kabilesh-Raj-T.github.io/EVCS"

      # 5️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 6️⃣ Build React app
      - name: Build project
        run: npm run build

      # 7️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          force_orphan: true
